import { FormData } from "./schema";

export const defaultValues: FormData = {
  pitch: "",
  projectClient: "",
  period: "",
  role: "",
  stakeholders: "",
  targetAudience: "",
  scope: [],
  context: "",
  pains: [],
  baseline: { timeToCompetency: "", completionRate: "", csat: "", businessKpi: "" },
  constraints: [],
  hypotheses: [],
  learningObjectives: [""],
  kirkpatrick: {
    l1Target: "",
    l2Target: "",
    l3Target: "",
    l4Target: "",
    plan: { what: "", when: "", where: "", tool: "", owner: "" },
  },
  scrum: {
    epic: "",
    sprintLength: "2 semaines",
    ceremonies: ["Planning", "Daily", "Review", "Rétrospective"],
    metrics: ["Vélocité", "Lead time", "Défauts", "Satisfaction"],
    stories: [{ asA: "", iWant: "", soThat: "", acceptanceCriteria: "", estimate: 1 }],
    dor: ["Story claire", "Dépendances levées", "Design/tech validés"],
    dod: [
      "Fonctionnel validé",
      "Accessibilité WCAG AA",
      "Traçabilité xAPI/SCORM",
      "Tests verts",
      "Documentation à jour",
    ],
  },
  addie: { analysis: [], design: [], development: [], implementation: [], evaluation: [] },
  results: { indicators: [], highlights: [] },
  proofs: { demo: "", deliverables: [], codeRepo: "", dashboard: "", testimonials: [] },
  learnings: { worked: [], change: [], next: [] },
  accessibilityChecklist: [],
  risks: [],
  raci: [],
  annexes: { xapi: "", storyTemplate: "", links: [] },
};

export const demoData: FormData = {
  ...defaultValues,
  pitch: "Onboarding dev : parcours mesurable, -40% time-to-productivity",
  projectClient: "TechCorp",
  period: "Q1–Q2 2025",
  role: "Lead ID & Dev Front",
  targetAudience: "Nouveaux devs (JS/TS), 30/mois",
  scope: ["E-learning", "Portail web", "Dashboard LRS"],
  context: "Hyper-croissance produit. Onboarding long et hétérogène, pas de tracking fin. Besoin d'itérations rapides.",
  pains: ["Onboarding 10 jours", "Complétion 58%", "Peu de transfert post-formation"],
  baseline: { timeToCompetency: "10j", completionRate: "58%", csat: "3.8/5", businessKpi: "T2M élevé" },
  constraints: ["Disponibilité SME limitée", "Time-to-market court"],
  learningObjectives: [
    "Appliquer le workflow de dev interne",
    "Configurer l'environnement en <30 min",
    "Livrer une PR conforme à la DoD",
  ],
  kirkpatrick: {
    l1Target: "CSAT ≥ 4.5/5",
    l2Target: "Post-test ≥ 80%",
    l3Target: "Application à J+30 confirmée par manager",
    l4Target: "Time-to-competency 10→6j",
    plan: {
      what: "L1–L4",
      when: "Fin module / J+30 / Trimestriel",
      where: "LMS / LRS / BI",
      tool: "xAPI",
      owner: "ID Lead",
    },
  },
  scrum: {
    ...defaultValues.scrum,
    epic: "Réduire le temps d'autonomie des nouveaux devs",
    stories: [
      {
        asA: "Nouveau dev",
        iWant: "Un portail onboarding",
        soThat: "Je deviens autonome en 6j",
        acceptanceCriteria: "Parcours 30-60-90, checklists, quiz",
        estimate: 5,
      },
    ],
  },
  results: {
    indicators: [
      { name: "Time-to-competency (jours)", baseline: "10", target: "6", actual: "", gap: "" },
      { name: "Complétion (%)", baseline: "58", target: "90", actual: "", gap: "" },
    ],
    highlights: ["-40% temps d'autonomie", "+32 pts complétion", "CSAT 4.6/5"],
  },
  proofs: {
    demo: "https://exemple.demo/video",
    deliverables: ["SCORM d'exemple", "Storyboard annoté"],
    codeRepo: "https://github.com/you/repo",
    dashboard: "https://bi.example.com",
    testimonials: ['"Claire et efficace" — Manager, 2025-06'],
  },
  learnings: { worked: ["Micro-modules + cas"], change: ["Plus d’exemples backend"], next: ["A/B test parcours"] },
  accessibilityChecklist: ["Contraste OK", "Clavier OK", "Sous-titres vidéos"],
  risks: [{ risk: "SME indisponible", probability: "M", impact: "H", response: "Timebox + validations", owner: "PO" }],
  raci: [{ task: "Analyse besoins", r: "ID Lead", a: "PO", c: "SME", i: "RH" }],
  annexes: { xapi: "answered/passed", storyTemplate: "En tant que..., je veux..., afin de...", links: ["Notion", "Drive"] },
};